****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZSPLIT_SS36																																
0110																																
750																																
                40																																
%_HEADER																																
SAPMZSPLIT_SS36                         0110I0110      4 29192 37  0  0 27121  0G E                              20240904140135																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
BOX_SELL		CHAR	 29	00	00	00	30	00	  1	  2		  0	  0	  0		  3	R				  0	  0	101							Carrier		
SCARR-CARRID	2	CHAR	 16	30	00	00	30	00	  2	  3		  0	  0	  0		  0			CAR		  0	  0								Ç×°ø»ç	                                                                                                                                                                                                                                                        X	
SCARR-CARRID	C	CHAR	  3	A0	00	80	00	00	  2	 20		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
BTN_SEARCH		CHAR	 31	00	00	00	30	00	  4	  3		  0	  0	  0		 28	P				  0	  0	102							@13@ Search	                                                                                                                                                                        SEAR	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0110.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0110.																																
