****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZSPLIT_SS36																																
0100																																
750																																
                40																																
%_HEADER																																
SAPMZSPLIT_SS36                         0100 0100     27120192 37  0  0 27120  0G E                              20240904144102																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SPLITTER			120	08	00	00	00	00	  1	  2		101	 30	  1		 27	X				  0	  0	101									
LEFT			120	00	C0	00	00	00	  1	  2	X	101	  1	  1		 27	B				  1	  1	102									
RIGHT			120	00	C0	00	00	00	  1	  2	X	101	  2	  1		 27	B				  1	  1	103									
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________	                                       00	
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0100.																																
  MODULE init_splitter. "스플릿 컨테이너 생성																																
  MODULE set_sash.																																
																																
  "서브스크린 호출(왼쪽, 오른쪽)																																
   CALL SUBSCREEN LEFT INCLUDING sy-cprog '0110'.																																
   CALL SUBSCREEN RIGHT INCLUDING sy-cprog '0120'.																																
*																																
PROCESS AFTER INPUT.																																
  CALL SUBSCREEN LEFT.																																
  CALL SUBSCREEN RIGHT.																																
																																
  MODULE get_sash.																																
																																
  MODULE USER_COMMAND_0100.																																
