****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZSPLIT_SS36																																
0120																																
750																																
                40																																
%_HEADER																																
SAPMZSPLIT_SS36                         0120I0120      5 66192 37  0  0 27121  0G E                              20240904140224																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SCARR-CARRID	2	CHAR	 16	30	00	00	30	00	  1	  2		  0	  0	  0		  0			CAR		  0	  0								항공사	                                                                                                                                                                                                                                                        X	
SCARR-CARRID	C	CHAR	  3	A0	00	80	30	00	  1	 19		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
SCARR-CARRNAME	2	CHAR	 16	30	02	00	30	00	  3	  2		  0	  0	  0		  0					  0	  0								항공사	                                                                                                                                                                                                                                                        X	
SCARR-CARRNAME	C	CHAR	 20	A0	02	80	30	00	  3	 19		  0	  0	  0		  0					 40	  0								____________________	                                       00	
SCARR-CURRCODE	2	CHAR	 16	30	00	04	30	00	  4	  2		  0	  0	  0		  0					  0	  0								항공사 통화	                                                                                                                                                                                                                                                        X	
SCARR-CURRCODE	C	CUKY	  5	A0	00	84	30	08	  4	 19		  0	  0	  0		  0					 10	  0								_____	X                                      00	
SCARR-URL	2	CHAR	  3	30	02	00	30	00	  5	  2		  0	  0	  0		  0					  0	  0								URL	                                                                                                                                                                                                                                                        X	
SCARR-URL	C	CHAR	255	B1	02	80	30	00	  5	 19		  0	  0	  0		 49					255	  0								____________________________________________________________________________________________________________________________________	                                       00	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0120.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0120.																																
