****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZCONN_SS36																																
0220																																
750																																
                40																																
%_HEADER																																
SAPMZCONN_SS36                          0220I0220      2 20192 37  0  0 27121  0G E                              20240902145255																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SDYN_CONN-AIRPFROM	2	CHAR	 15	30	00	00	30	00	  1	  3		  0	  0	  0		  0					  0	  0								출발 공항	                                                                                                                                                                                                                                                        X	
SDYN_CONN-AIRPFROM	C	CHAR	  3	A0	00	80	30	00	  1	 19		  0	  0	  0		  0					  6	  0								___	                                       00	
SDYN_CONN-AIRPTO	2	CHAR	 15	30	00	00	30	00	  2	  3		  0	  0	  0		  0					  0	  0								도착 공항	                                                                                                                                                                                                                                                        X	
SDYN_CONN-AIRPTO	C	CHAR	  3	A0	00	80	30	00	  2	 19		  0	  0	  0		  0					  6	  0								___	                                       00	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0220.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0220.																																
