****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZCONN_SS36																																
0200																																
750																																
                40																																
%_HEADER																																
SAPMZCONN_SS36                          0200 0200     21 56192 37  0  0 27127  0G E                              20240903105451																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
BOX_KEY		CHAR	 55	00	00	00	30	00	  1	  3		  0	  0	  0		  4	R				  0	  0	102							Key		
SDYN_CONN-CARRID	2	CHAR	 16	30	00	04	38	00	  2	  5		  0	  0	  0		  0			CAR		  0	  0								항공사	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CARRID	C	CHAR	  3	A0	00	84	30	08	  2	 23		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
SDYN_CONN-CONNID	2	CHAR	 15	30	00	04	38	00	  3	  5		  0	  0	  0		  0			CON		  0	  0								항공편 번호	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CONNID	N	NUMC	  4	A0	00	84	30	08	  3	 23		  0	  0	  0		  0			CON		  8	  0								____	X                                      00	
BOX_FROM		CHAR	 55	00	00	00	30	00	  5	  3		  0	  0	  0		  4	R				  0	  0	103							From Information		
SDYN_CONN-COUNTRYFR	2	CHAR	 12	30	00	00	30	00	  6	  5		  0	  0	  0		  0			LND		  0	  0								국가	                                                                                                                                                                                                                                                        X	
SDYN_CONN-COUNTRYFR	C	CHAR	  3	A0	00	80	00	00	  6	 23		  0	  0	  0		  0			LND		  6	  0				XYZ				___	                                       00	
SDYN_CONN-CITYFROM	2	CHAR	 11	30	00	00	30	00	  7	  5		  0	  0	  0		  0					  0	  0								출발 도시	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CITYFROM	C	CHAR	 20	A0	00	80	00	00	  7	 23		  0	  0	  0		  0					 40	  0				XYZ				____________________	                                       00	
BOX_To		CHAR	 55	00	00	00	30	00	  9	  3		  0	  0	  0		  5	R				  0	  0	104							To Information		
SDYN_CONN-COUNTRYTO	2	CHAR	 12	30	00	00	30	00	 10	  5		  0	  0	  0		  0			LND		  0	  0								국가	                                                                                                                                                                                                                                                        X	
SDYN_CONN-COUNTRYTO	C	CHAR	  3	A0	00	80	00	00	 10	 23		  0	  0	  0		  0			LND		  6	  0				XYZ				___	                                       00	
SDYN_CONN-CITYTO	2	CHAR	 17	30	00	00	30	00	 11	  5		  0	  0	  0		  0					  0	  0								도착 도시	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CITYTO	C	CHAR	 20	A0	00	80	00	00	 11	 23		  0	  0	  0		  0					 40	  0				XYZ				____________________	                                       00	
MY_TABSTRIP			 55	08	00	00	00	00	 14	  3	J	101	  1	  1		  7	I				  7	 55										
TAB1		CHAR	 11	00	00	00	30	00	  1	  1	I	101	  1	  1		  0	P				  0	  0	105	SUB1						Status Info	                                                                                                                                                                       PTAB1	
TAB2		CHAR	 13	00	00	00	30	00	  1	  2	I	101	  1	  1		  0	P				  0	  0	106	SUB2						Distance info	                                                                                                                                                                       PTAB2	
TAB3		CHAR	 17	00	00	00	30	00	  1	  3	I	101	  1	  1		 15	P				  0	  0	107	SUB3						@UE@ Airport Info	                                                                                                                                                                       PTAB3	
TAB4		CHAR	 14	00	00	00	30	00	  1	  4	I	101	  1	  1		 12	P				  0	  0	108	SUB4						@9R@ Time Info	                                                                                                                                                                       PTAB4	
SUB1			 51	00	C0	00	30	00	 16	  4	I	101	  0	  0		  4	B				  3	  3	109									
SUB2			 53	00	C0	00	30	00	 16	  4	I	101	  0	  0		  4	B				  3	  3	110									
SUB3			 53	00	C0	00	30	00	 16	  4	I	101	  0	  0		  4	B				  3	  3	111									
SUB4			 53	00	C0	00	30	00	 16	  4	I	101	  0	  0		  4	B				  3	  3	112									
BTN_TOGGLE	0	CHAR	 21	00	00	00	30	00	 21	  3		  0	  0	  0		  0	P				  0	  0	113							Display / Change	                                                                                                                                                                        TOGG	
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE clear_ok_code.																																
  MODULE status_0200.																																
  MODULE modify_screen. "D:조회 모드 / U:수정 모드																																
  MODULE set_icon. "아이콘 결정.																																
  MODULE set_distance.																																
*  MODULE set_subscr. "서브스크린 번호 결정.																																
																																
  "서브 스크린 호출																																
  "sy-cprog(프로그램)에 있는 gv_dynnr(화면)을																																
  "sub(subscreen name)에 껴넣겠다																																
*  CALL SUBSCREEN sub																																
*  INCLUDING sy-cprog gv_dynnr.																																
																																
  "탭스크린을 위한 서브스크린 호출하기																																
  CALL SUBSCREEN sub1																																
    INCLUDING sy-cprog '0230'.																																
  CALL SUBSCREEN sub2																																
    INCLUDING sy-cprog '0240'.																																
  CALL SUBSCREEN sub3																																
    INCLUDING sy-cprog '0220'.																																
  CALL SUBSCREEN sub4																																
    INCLUDING sy-cprog '0210'.																																
																																
PROCESS AFTER INPUT.																																
																																
*  CALL SUBSCREEN sub.																																
  CALL SUBSCREEN sub1.																																
  CALL SUBSCREEN sub2.																																
  CALL SUBSCREEN sub3.																																
  CALL SUBSCREEN sub4.																																
																																
  CHAIN.																																
    FIELD: sdyn_conn-countryfr,																																
           sdyn_conn-cityfrom																																
    MODULE check_conn_fr ON CHAIN-REQUEST.																																
  ENDCHAIN.																																
																																
  CHAIN.																																
    FIELD: sdyn_conn-countryto,																																
           sdyn_conn-cityto																																
    MODULE check_conn_to ON CHAIN-REQUEST.																																
  ENDCHAIN.																																
																																
  MODULE user_command_0200.																																
