****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZCONN_SS36																																
0210																																
750																																
                40																																
%_HEADER																																
SAPMZCONN_SS36                          0210I0210      2 24192 37  0  0 27122  0G E                              20240902151218																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SDYN_CONN-DEPTIME	2	CHAR	 15	30	00	00	30	00	  1	  2		  0	  0	  0		  0					  0	  0								출발	                                                                                                                                                                                                                                                        X	
SDYN_CONN-DEPTIME	T	TIME	  8	A0	00	80	30	08	  1	 18		  0	  0	  0		  0					 12	  0								________	X                                      00	
SDYN_CONN-ARRTIME	2	CHAR	 15	30	00	00	30	00	  2	  2		  0	  0	  0		  0					  0	  0								도착 시간	                                                                                                                                                                                                                                                        X	
SDYN_CONN-ARRTIME	T	TIME	  8	A0	00	80	30	08	  2	 18		  0	  0	  0		  0					 12	  0								________	X                                      00	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0210.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0210.																																
