****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZCONN_SS36																																
0230																																
750																																
                40																																
%_HEADER																																
SAPMZCONN_SS36                          0230I0230      1 11192 37  0  0 27121  0G E                              20240903094240																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
LBL_STA	C	CHAR	  7	00	00	00	30	00	  1	  3		  0	  0	  0		  0					  0	  0								Status		
GV_INT	C	CHAR	 33	80	00	80	32	00	  1	 11		  0	  0	  0		  2					  0	  0								@00@_____________________________		
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0230.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0230.																																
