****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZBOOKINGS_LOCK_SS36																																
0300																																
750																																
                40																																
%_HEADER																																
SAPMZBOOKINGS_LOCK_SS36                 0300 0300     20 82192 37  0  0 21 83  0G D                              20240906132239																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SDYN_CONN-CARRID	2	CHAR	 16	30	00	04	30	00	  1	  2		  0	  0	  0		  0			CAR		  0	  0								항공사	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CARRID	C	CHAR	  3	A0	00	84	30	08	  1	 19		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
SDYN_CONN-CONNID	2	CHAR	 15	30	00	04	30	00	  2	  2		  0	  0	  0		  0			CON		  0	  0								항공편 번호	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CONNID	N	NUMC	  4	A0	00	84	30	08	  2	 19		  0	  0	  0		  0			CON		  8	  0								____	X                                      00	
SDYN_CONN-FLDATE	2	CHAR	  9	30	00	00	30	00	  3	  2		  0	  0	  0		  0			DAY		  0	  0								일자	                                                                                                                                                                                                                                                        X	
SDYN_CONN-FLDATE	D	DATE	 10	A0	00	80	30	08	  3	 19		  0	  0	  0		  0			DAY		 16	  0								__________	X                                      00	
TAB			 82	08	30	00	00	00	  6	  2	J	101	  1	  1		 15	I				  4	  7										
PUSH1		CHAR	  7	00	00	00	30	00	  1	  1	I	101	  1	  1		  0	P				  0	  0	102	TAB_SUB						Booking	                                                                                                                                                                        BOOK	
PUSH2		CHAR	 12	00	00	00	30	00	  1	  2	I	101	  1	  1		  0	P				  0	  0	103	TAB_SUB						Flt details	                                                                                                                                                                        DETFLT	
PUSH3		CHAR	 18	00	00	00	30	00	  1	  3	I	101	  1	  1		  0	P				  0	  0	104	TAB_SUB						Connection details	                                                                                                                                                                        DETCON	
TAB_SUB			 80	00	F0	00	30	00	  8	  3	I	101	  0	  0		 12	B				  1	  1	105									
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
																																
PROCESS BEFORE OUTPUT.																																
  MODULE status_0300.																																
  MODULE tabstrip_init.																																
  CALL SUBSCREEN tab_sub INCLUDING sy-cprog gv_screen_no.																																
  MODULE clear_okcode.																																
																																
																																
PROCESS AFTER INPUT.																																
  MODULE exit AT EXIT-COMMAND.																																
  CALL SUBSCREEN tab_sub.																																
  MODULE user_command_0300.																																
