****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZBOOKINGS_LOCK_SS36																																
0301																																
750																																
                40																																
%_HEADER																																
SAPMZBOOKINGS_LOCK_SS36                 0301I0301     10 62192 37  0  0 21 83  0G D                              20240906132239																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SDYN_BOOK-BOOKID	2	CHAR	 15	30	00	00	30	00	  1	  2		  0	  0	  0		  0			BOK		  0	  0								예약 번호	                                                                                                                                                                                                                                                        X	
SDYN_BOOK-BOOKID	N	NUMC	  8	A0	00	80	00	08	  1	 18		  0	  0	  0		  8			BOK		 16	  0								________	X                                      00	
SDYN_BOOK-CUSTOMID	2	CHAR	 15	30	00	04	30	00	  2	  2		  0	  0	  0		  0			CSM		  0	  0								고객 번호	                                                                                                                                                                                                                                                        X	
SDYN_BOOK-CUSTOMID	N	NUMC	  8	A0	0C	84	00	08	  2	 18		  0	  0	  0		  0			CSM		 16	  0			SCUS					________	X                                      00	
SDYN_BOOK-ORDER_DATE	2	CHAR	 15	30	00	00	30	00	  4	  2		  0	  0	  0		  0					  0	  0								예약일	                                                                                                                                                                                                                                                        X	
SDYN_BOOK-ORDER_DATE	D	DATE	 10	A0	00	80	00	08	  4	 18		  0	  0	  0		  0					 16	  0								__________	X                                      00	
SDYN_BOOK-SMOKER	C	CHAR	  1	A0	00	81	00	08	  4	 47		  0	  0	  0		  0	C				  2	  0	101							_	X                                      00	
SDYN_BOOK-SMOKER	2	CHAR	 15	30	00	01	30	00	  4	 49		  0	  0	  0		  0	C				  0	  0	101							흡연자		
SDYN_BOOK-COUNTER	2	CHAR	 15	30	00	04	30	00	  5	  2		  0	  0	  0		  0					  0	  0								영업소	                                                                                                                                                                                                                                                        X	
SDYN_BOOK-COUNTER	N	NUMC	  8	A0	00	84	00	08	  5	 18		  0	  0	  0		  0					 16	  0								________	X                                      00	
SDYN_BOOK-INVOICE	C	CHAR	  1	A0	00	81	00	08	  5	 47		  0	  0	  0		  0	C				  2	  0	102							_	X                                      00	
SDYN_BOOK-INVOICE	2	CHAR	 12	30	00	01	30	00	  5	 49		  0	  0	  0		  0	C				  0	  0	102							송장플래그		
SDYN_BOOK-AGENCYNUM	2	CHAR	 12	30	00	04	30	00	  6	  2		  0	  0	  0		  0			AGENCYNUM		  0	  0								여행사 번호	                                                                                                                                                                                                                                                        X	
SDYN_BOOK-AGENCYNUM	N	NUMC	  8	A0	00	84	00	08	  6	 18		  0	  0	  0		  0			AGENCYNUM		 16	  0								________	X                                      00	
SDYN_BOOK-LUGGWEIGHT	2	CHAR	 15	30	00	00	30	00	  7	  2		  0	  0	  0		  0					  0	  0								수하물 중량	                                                                                                                                                                                                                                                        X	
SDYN_BOOK-LUGGWEIGHT	P	QUAN	 10	A0	00	80	00	00	  7	 18		  0	  0	  0		  0					  8	  4		SDYN_BOOK-WUNIT						_.___,____	                                       00	
SDYN_BOOK-WUNIT	C	UNIT	  3	A0	02	80	00	00	  7	 29		  0	  0	  0		  0				CUNIT	  6	  0								___	                                       00	
SDYN_BOOK-FORCURAM	2	CHAR	 15	30	00	00	30	00	  8	  2		  0	  0	  0		  0					  0	  0								금액	                                                                                                                                                                                                                                                        X	
SDYN_BOOK-FORCURAM	P	CURR	 20	A0	00	80	00	00	  8	 18		  0	  0	  0		  0					 15	  2		SDYN_BOOK-FORCURKEY						____________________	                                       00	
SDYN_BOOK-FORCURKEY	C	CUKY	  5	A0	00	84	00	08	  8	 39		  0	  0	  0		  0					 10	  0								_____	X                                      00	
SDYN_BOOK-CUSTTYPE	2	CHAR	 15	30	00	01	30	00	  9	  2		  0	  0	  0		  0					  0	  0								B/P 고객	                                                                                                                                                                                                                                                        X	
SDYN_BOOK-CUSTTYPE	C	CHAR	  1	A0	00	81	00	08	  9	 18		  0	  0	  0		  0					  2	  0								_	X                                      00	
SDYN_BOOK-CLASS	2	CHAR	  8	30	00	01	30	00	 10	  2		  0	  0	  0		  0					  0	  0								클래스	                                                                                                                                                                                                                                                        X	
SDYN_BOOK-CLASS	C	CHAR	  1	A0	00	81	00	08	 10	 18		  0	  0	  0		  0					  2	  0								_	X                                      00	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
																																
PROCESS BEFORE OUTPUT.																																
* MODULE hide_bookid.																																
  MODULE initialize_sdyn_book.																																
																																
*																																
PROCESS AFTER INPUT.																																
