****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZ_STUDENTSS36																																
0100																																
750																																
                40																																
%_HEADER																																
SAPMZ_STUDENTSS36                       0100 0100      9 36192 37  0  0 27122  0G E                              20240904173458																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
BOX_STUDENT		CHAR	 36	00	00	00	30	00	  1	  2		  0	  0	  0		  4	R				  0	  0	101							Student Info		
ZSTD_SS36-MAJOR	2	CHAR	 20	30	00	04	30	00	  2	  4		  0	  0	  0		  0					  0	  0								Major	                                                                                                                                                                                                                                                        X	
ZSTD_SS36-MAJOR	N	NUMC	  3	A0	00	A4	00	08	  2	 25		  0	  0	  0		  0					  6	  0								___	X                                      00	
ZSTD_SS36-ID	0	CHAR	 20	30	00	00	30	00	  3	  4		  0	  0	  0		  0					  0	  0								Student ID	                                                                                                                                                                                                                                                        X	
ZSTD_SS36-ID	N	NUMC	  8	A0	00	A0	00	08	  3	 25		  0	  0	  0		  0					 16	  0								________	X                                      00	
VOX_MODE		CHAR	 36	00	00	00	30	00	  5	  2		  0	  0	  0		  4	R				  0	  0	102							Mode		
GS_MODE-DISPLAY	C	CHAR	  1	80	00	80	00	00	  6	  4		  0	  0	  0		  0	A				  0	  0	103								                                                                                                                                                                        MODE	
GS_MODE-DISPLAY	0	CHAR	 12	00	00	00	30	00	  6	  6		  0	  0	  0		 10	A				  0	  0	103							@Y2@ Display		
GS_MODE-CHANGE	C	CHAR	  1	80	00	80	00	00	  7	  4		  0	  0	  0		  0	A				  0	  0	103								                                                                                                                                                                        MODE	
GS_MODE-CHANGE	0	CHAR	 11	00	00	00	30	00	  7	  6		  0	  0	  0		  9	A				  0	  0	103							@HD@ Change		
BTN_MAINTAIN		CHAR	 39	00	00	00	30	00	  9	  3		  0	  0	  0		 34	P				  0	  0	104							@0V@ Maintain	                                                                                                                                                                        MAIN	
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE clear_ok_code.																																
  MODULE status_0100.																																
*																																
PROCESS AFTER INPUT.																																
  MODULE exit AT EXIT-COMMAND.																																
																																
  CHAIN.																																
    FIELD: zstd_ss36-major, zstd_ss36-id																																
    MODULE check_major ON REQUEST.																																
  ENDCHAIN.																																
																																
  MODULE get_data.																																
  MODULE get_gender.																																
  MODULE get_subjects.																																
																																
  MODULE user_command_0100.																																
