****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZBC410_SOLUTION_SS36																																
0120																																
750																																
                40																																
%_HEADER																																
SAPMZBC410_SOLUTION_SS36                0120I0120      9 44192 37  0  0 27121  0G E                              20240902160133																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SAPLANE-PLANETYPE	2	CHAR	 11	30	00	00	30	00	  1	  3		  0	  0	  0		  0					  0	  0								항공기 유형	                                                                                                                                                                                                                                                        X	
SAPLANE-PLANETYPE	C	CHAR	 10	A0	00	80	31	00	  1	 24		  0	  0	  0		  0					 20	  0								__________	                                       00	
SAPLANE-SEATSMAX	2	CHAR	 20	30	00	01	30	00	  2	  3		  0	  0	  0		  0					  0	  0								일반석 최대 정원	                                                                                                                                                                                                                                                        X	
SAPLANE-SEATSMAX	X	INT4	 10	A0	00	81	31	08	  2	 24		  0	  0	  0		  0					 10	  0								__________	X                                      00	
SAPLANE-CON_UNIT	2	CHAR	  4	30	00	00	30	00	  3	  3		  0	  0	  0		  0					  0	  0								단위	                                                                                                                                                                                                                                                        X	
SAPLANE-CON_UNIT	C	UNIT	  3	A0	00	80	31	00	  3	 24		  0	  0	  0		  0					  6	  0								___	                                       00	
SAPLANE-TANKCAP	2	CHAR	 20	30	00	00	30	00	  4	  3		  0	  0	  0		  0					  0	  0								연료	                                                                                                                                                                                                                                                        X	
SAPLANE-TANKCAP	P	QUAN	 20	A0	00	80	31	00	  4	 24		  0	  0	  0		  0					 16	  4		SAPLANE-CAP_UNIT						___.___.___.___,____	                                       00	
SAPLANE-WEIGHT	2	CHAR	 15	30	00	00	30	00	  5	  3		  0	  0	  0		  0					  0	  0								중량	                                                                                                                                                                                                                                                        X	
SAPLANE-WEIGHT	P	QUAN	 18	A0	00	80	31	00	  5	 24		  0	  0	  0		  0					 14	  4		SAPLANE-WEI_UNIT						_.___.___.___,____	                                       00	
SAPLANE-WEI_UNIT	2	CHAR	 15	30	00	00	30	00	  6	  3		  0	  0	  0		  0					  0	  0								단위	                                                                                                                                                                                                                                                        X	
SAPLANE-WEI_UNIT	C	UNIT	  3	A0	00	80	31	00	  6	 24		  0	  0	  0		  0					  6	  0								___	                                       00	
SAPLANE-OP_SPEED	2	CHAR	 15	30	00	00	30	00	  7	  3		  0	  0	  0		  0					  0	  0								속도	                                                                                                                                                                                                                                                        X	
SAPLANE-OP_SPEED	P	QUAN	 22	A0	00	80	31	00	  7	 24		  0	  0	  0		  0					 17	  4		SAPLANE-SPEED_UNIT						_.___.___.___.___,____	                                       00	
SAPLANE-SPEED_UNIT	2	CHAR	 15	30	00	00	30	00	  8	  3		  0	  0	  0		  0					  0	  0								단위	                                                                                                                                                                                                                                                        X	
SAPLANE-SPEED_UNIT	C	UNIT	  3	A0	00	80	31	00	  8	 24		  0	  0	  0		  0					  6	  0								___	                                       00	
SAPLANE-PRODUCER	2	CHAR	 15	30	00	00	30	00	  9	  3		  0	  0	  0		  0					  0	  0								제조업체	                                                                                                                                                                                                                                                        X	
SAPLANE-PRODUCER	C	CHAR	  5	A0	00	80	31	00	  9	 24		  0	  0	  0		  0					 10	  0								_____	                                       00	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0120.																																
  MODULE get_saplane.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0120.																																
