****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZBC410_SOLUTION_SS36																																
0130																																
750																																
                40																																
%_HEADER																																
SAPMZBC410_SOLUTION_SS36                0130I0130     15 90192 37  0  0 27124  0G E                              20240904200918																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
MY_TABLE_CONTROL			 90	F9	F8	00	00	00	  1	  2	E	101	  1	  1		 14	T				  0	  0									                                                                                                                                                                                                                                    SUB0130	
SDYN_BOOK-BOOKID	2	CHAR	 15	30	00	00	30	80	  1	  1	T	101	  1	  1		  8			BOK		  0	  0								예약 번호		
SDYN_BOOK-CUSTOMID	2	CHAR	 15	30	00	04	30	80	  1	  2	T	101	  1	  1		  8			CSM		  0	  0								고객 번호		
SDYN_BOOK-CUSTTYPE	2	CHAR	 15	30	00	01	30	80	  1	  3	T	101	  1	  1		  1					  0	  0								B/P 고객		
SDYN_BOOK-SMOKER	2	CHAR	 15	30	00	01	30	80	  1	  4	T	101	  1	  1		  1					  0	  0								흡연자		
SDYN_BOOK-LUGGWEIGHT	2	CHAR	 15	30	00	00	30	80	  1	  5	T	101	  1	  1		 10					  0	  0								수하물 중량		
SDYN_BOOK-WUNIT	2	CHAR	 15	30	02	00	30	80	  1	  6	T	101	  1	  1		  3					  0	  0								단위		
SDYN_BOOK-INVOICE	2	CHAR	 12	30	00	01	30	80	  1	  7	T	101	  1	  1		  1					  0	  0								송장플래그		
SDYN_BOOK-CLASS	2	CHAR	  8	30	00	01	30	80	  1	  8	T	101	  1	  1		  1					  0	  0								클래스		
SDYN_BOOK-FORCURAM	2	CHAR	 15	30	00	00	30	80	  1	  9	T	101	  1	  1		 20					  0	  0								금액		
SDYN_BOOK-FORCURKEY	2	CHAR	 15	30	00	04	30	80	  1	 10	T	101	  1	  1		  5					  0	  0								지급통화		
SDYN_BOOK-LOCCURAM	2	CHAR	 15	30	00	00	30	80	  1	 11	T	101	  1	  1		 20					  0	  0								금액		
SDYN_BOOK-LOCCURKEY	2	CHAR	 16	30	00	04	30	80	  1	 12	T	101	  1	  1		  5					  0	  0								항공사 통화		
SDYN_BOOK-ORDER_DATE	2	CHAR	 15	30	00	00	30	80	  1	 13	T	101	  1	  1		 10					  0	  0								예약일		
SDYN_BOOK-COUNTER	2	CHAR	 15	30	00	04	30	80	  1	 14	T	101	  1	  1		  8					  0	  0								영업소		
SDYN_BOOK-AGENCYNUM	2	CHAR	 12	30	00	04	30	80	  1	 15	T	101	  1	  1		  8			AGENCYNUM		  0	  0								여행사 번호		
SDYN_BOOK-MARK	C	CHAR	  1	80	00	80	00	20	  1	  0	T	101	  1	  1		  1	C				  0	  0	102									
SDYN_BOOK-BOOKID	N	NUMC	  8	A0	00	80	30	28	  1	  1	T	101	  1	  1		  8			BOK		 16	  0								________	X                                      00	
SDYN_BOOK-CUSTOMID	N	NUMC	  8	A0	00	84	30	28	  1	  2	T	101	  1	  1		  8			CSM		 16	  0								________	X                                      00	
SDYN_BOOK-CUSTTYPE	C	CHAR	  1	A0	00	81	30	08	  1	  3	T	101	  1	  1		  1					  2	  0								_	X                                      00	
SDYN_BOOK-SMOKER	C	CHAR	  1	A0	00	81	30	08	  1	  4	T	101	  1	  1		  1					  2	  0								_	X                                      00	
SDYN_BOOK-LUGGWEIGHT	P	QUAN	 10	A0	00	80	30	00	  1	  5	T	101	  1	  1		 10					  8	  4		SDYN_BOOK-WUNIT						_.___,____	                                       00	
SDYN_BOOK-WUNIT	C	UNIT	  3	A0	02	80	30	00	  1	  6	T	101	  1	  1		  3				CUNIT	  6	  0								___	                                       00	
SDYN_BOOK-INVOICE	C	CHAR	  1	A0	00	81	30	08	  1	  7	T	101	  1	  1		  1					  2	  0								_	X                                      00	
SDYN_BOOK-CLASS	C	CHAR	  1	A0	00	81	30	08	  1	  8	T	101	  1	  1		  1					  2	  0								_	X                                      00	
SDYN_BOOK-FORCURAM	P	CURR	 20	A0	00	80	30	00	  1	  9	T	101	  1	  1		 20					 15	  2		SDYN_BOOK-FORCURKEY						____________________	                                       00	
SDYN_BOOK-FORCURKEY	C	CUKY	  5	A0	00	84	30	08	  1	 10	T	101	  1	  1		  5					 10	  0								_____	X                                      00	
SDYN_BOOK-LOCCURAM	P	CURR	 20	A0	00	80	30	00	  1	 11	T	101	  1	  1		 20					 15	  2		SDYN_BOOK-LOCCURKEY						____________________	                                       00	
SDYN_BOOK-LOCCURKEY	C	CUKY	  5	A0	00	84	30	08	  1	 12	T	101	  1	  1		  5					 10	  0								_____	X                                      00	
SDYN_BOOK-ORDER_DATE	D	DATE	 10	A0	00	80	30	08	  1	 13	T	101	  1	  1		 10					 16	  0								__________	X                                      00	
SDYN_BOOK-COUNTER	N	NUMC	  8	A0	00	84	30	08	  1	 14	T	101	  1	  1		  8					 16	  0								________	X                                      00	
SDYN_BOOK-AGENCYNUM	N	NUMC	  8	A0	00	84	30	08	  1	 15	T	101	  1	  1		  8			AGENCYNUM		 16	  0								________	X                                      00	
SELECT_ALL		CHAR	  6	00	00	00	30	00	 15	  2		  0	  0	  0		  2	P				  0	  0	103							@4B@ #	                                                                                                                                                                        SELE	
DESELECT_ALL		CHAR	  6	00	00	00	30	00	 15	  5		  0	  0	  0		  2	P				  0	  0	104							@4D@ #	                                                                                                                                                                        DESE	
MY_TABLE_CONTROL-V_GRID	C	CHAR	  1	80	00	80	00	00	 15	 11		  0	  0	  0		  0	C				  0	  0	105								                                                                                                                                                                        VER	
MY_TABLE_CONTROL-V_GRID	0	CHAR	 10	00	00	00	30	00	 15	 13		  0	  0	  0		  0	C				  0	  0	105							Vert.lines		
MY_TABLE_CONTROL-H_GRID	C	CHAR	  1	80	00	80	00	00	 15	 26		  0	  0	  0		  0	C				  0	  0	106								                                                                                                                                                                        HOR	
MY_TABLE_CONTROL-H_GRID	0	CHAR	 11	00	00	00	30	00	 15	 28		  0	  0	  0		  0	C				  0	  0	106							Horiz.lines		
SMOKER	C	CHAR	  1	80	00	80	00	00	 15	 42		  0	  0	  0		  0	C				  0	  0	107								                                                                                                                                                                        SMOK	
SMOKER	0	CHAR	 17	00	00	00	30	00	 15	 44		  0	  0	  0		  0	C				  0	  0	107							Highlight Smokers		
P_SRTU		CHAR	  6	00	00	00	30	00	 15	 74		  0	  0	  0		  2	P				  0	  0	108							@3E@ #	                                                                                                                                                                        SRTU	
P_SRTD		CHAR	  4	00	00	00	30	00	 15	 77		  0	  0	  0		  2	P				  0	  0	109							@3F@	                                                                                                                                                                        SRTD	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0130.																																
  MODULE get_sbook.																																
 LOOP AT it_sdyn_book INTO wa_sdyn_book																																
                      WITH CONTROL my_table_control.																																
																																
   MODULE trans_to_tc.																																
   MODULE modify_tc_line.																																
																																
 ENDLOOP.																																
*																																
PROCESS AFTER INPUT.																																
																																
  LOOP AT it_sdyn_book.																																
    FIELD sdyn_book-mark																																
    MODULE trans_from_tc ON REQUEST.																																
  ENDLOOP.																																
																																
  MODULE USER_COMMAND_0130.																																
