****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZBC410_SOLUTION_SS36																																
0150																																
750																																
                40																																
%_HEADER																																
SAPMZBC410_SOLUTION_SS36                0150M0000      2 22192 37  0  0 27121  0G E                              20240830103055																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SYST-UZEIT	2	CHAR	 10	30	00	00	30	00	  2	  5		  0	  0	  0		  0					  0	  0								Time	                                                                                                                                                                                                                                                        X	
SYST-UZEIT	T	TIME	  8	A0	00	80	00	08	  2	 16		  0	  0	  0		  0					 12	  0								________	X                                      00	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE clear_ok_code.																																
  MODULE status_0150.																																
*																																
PROCESS AFTER INPUT.																																
  MODULE user_command_0150.																																
