****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZBC410_SOLUTION_SS36																																
0100																																
750																																
                40																																
%_HEADER																																
SAPMZBC410_SOLUTION_SS36                0100 0100     22 82192 37  0  0 27128  0G E                              20240903112859																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SDYN_CONN-CARRID	2	CHAR	 16	30	00	04	30	00	  1	  3		  0	  0	  0		  0			CAR		  0	  0								항공사	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CARRID	C	CHAR	 22	B0	0C	84	00	18	  1	 24		  0	  0	  0		 24			CAR		  6	  0								______________________	XDL                                    00	
SDYN_CONN-CONNID	2	CHAR	 15	30	00	04	30	00	  2	  3		  0	  0	  0		  0			CON		  0	  0								항공편 번호	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CONNID	N	NUMC	  4	A0	0C	A4	00	08	  2	 24		  0	  0	  0		  0			CON		  8	  0								____	X                                      00	
SDYN_CONN-FLDATE	2	CHAR	  9	30	00	00	30	00	  3	  3		  0	  0	  0		  0			DAY		  0	  0								일자	                                                                                                                                                                                                                                                        X	
SDYN_CONN-FLDATE	D	DATE	 10	A0	0C	A0	00	08	  3	 24		  0	  0	  0		  0			DAY		 16	  0								__________	X                                      00	
BOX_MODE		CHAR	 28	00	00	00	30	00	  3	 55		  0	  0	  0		  5	R				  0	  0	102							Mode		
SDYN_CONN-PRICE	2	CHAR	  9	30	00	00	30	00	  4	  3		  0	  0	  0		  0					  0	  0								항공 요금	                                                                                                                                                                                                                                                        X	
SDYN_CONN-PRICE	P	CURR	 20	A0	00	80	30	00	  4	 24		  0	  0	  0		  0					 15	  2		SDYN_CONN-CURRENCY						____________________	                                       00	
GS_MODE-VIEW	C	CHAR	  1	80	00	80	00	00	  4	 58		  0	  0	  0		  0	A				  0	  0	103								                                                                                                                                                                        MODE	
GS_MODE-VIEW	0	CHAR	  4	00	00	00	30	00	  4	 60		  0	  0	  0		  0	A				  0	  0	103							View		
SDYN_CONN-CURRENCY	2	CHAR	 16	30	00	04	30	00	  5	  3		  0	  0	  0		  0					  0	  0								항공사 통화	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CURRENCY	C	CUKY	  5	A0	00	84	30	08	  5	 24		  0	  0	  0		  0					 10	  0								_____	X                                      00	
GS_MODE-MAINTAIN_FLIGHTS	C	CHAR	  1	80	00	80	00	00	  5	 58		  0	  0	  0		  0	A				  0	  0	103								                                                                                                                                                                        MODE	
GS_MODE-MAINTAIN_FLIGHTS	0	CHAR	 16	00	00	00	30	00	  5	 60		  0	  0	  0		  0	A				  0	  0	103							Maintain flights		
SDYN_CONN-PLANETYPE	2	CHAR	 11	30	00	04	30	00	  6	  3		  0	  0	  0		  0					  0	  0								항공기 유형	                                                                                                                                                                                                                                                        X	
SDYN_CONN-PLANETYPE	C	CHAR	 10	A0	00	84	30	08	  6	 24		  0	  0	  0		  0					 20	  0								__________	X                                      00	
GS_MODE-MAINTAIN_BOOKINGS	C	CHAR	  1	80	00	80	00	00	  6	 58		  0	  0	  0		  0	A				  0	  0	103								                                                                                                                                                                        MODE	
GS_MODE-MAINTAIN_BOOKINGS	0	CHAR	 17	00	00	00	30	00	  6	 60		  0	  0	  0		  0	A				  0	  0	103							Maintain bookings		
SDYN_CONN-SEATSMAX	2	CHAR	 20	30	00	01	30	00	  7	  3		  0	  0	  0		  0					  0	  0								일반석 최대 정원	                                                                                                                                                                                                                                                        X	
SDYN_CONN-SEATSMAX	X	INT4	 10	A0	00	81	30	08	  7	 24		  0	  0	  0		  0					 10	  0								__________	X                                      00	
SDYN_CONN-SEATSOCC	2	CHAR	 15	30	00	01	30	00	  8	  3		  0	  0	  0		  0					  0	  0								예약된 일반석	                                                                                                                                                                                                                                                        X	
SDYN_CONN-SEATSOCC	X	INT4	 10	A0	00	81	30	08	  8	 24		  0	  0	  0		  0					 10	  0								__________	X                                      00	
SDYN_CONN-PAYMENTSUM	2	CHAR	 10	30	00	00	30	00	  9	  3		  0	  0	  0		  0					  0	  0								총계	                                                                                                                                                                                                                                                        X	
SDYN_CONN-PAYMENTSUM	P	CURR	 22	A0	00	80	30	00	  9	 24		  0	  0	  0		  0					 17	  2		SDYN_CONN-CURRENCY						______________________	                                       00	
MY_TABSTRIP			 81	08	30	00	00	00	 11	  3	J	101	  1	  1		 12	I				  6	 41										
P1		CHAR	 16	00	00	00	30	00	  1	  1	I	101	  1	  1		  0	P				  0	  0	104	SUB						View flight data	                                                                                                                                                                        FC1	
P2		CHAR	 32	00	00	00	30	00	  1	  2	I	101	  1	  1		  0	P				  0	  0	105	SUB						View technical data for aircraft	                                                                                                                                                                        FC2	
P3		CHAR	 17	00	00	00	30	00	  1	  3	I	101	  1	  1		  0	P				  0	  0	106	SUB						Maintain book-ing	                                                                                                                                                                        FC3	
SUB			 79	00	F0	00	30	00	 13	  4	I	101	  0	  0		  9	B				  3	 39	107									
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE status_0100.																																
  MODULE move_to_dynp.																																
  MODULE clear_ok_code.																																
  MODULE modify_screen.																																
  MODULE fill_dynnr.																																
																																
  CALL SUBSCREEN sub																																
       INCLUDING sy-cprog gv_dynnr.																																
																																
PROCESS AFTER INPUT.																																
  MODULE exit AT EXIT-COMMAND.																																
  CHAIN.																																
    "3개의 값 중에 하나라도 바뀌면 체크하겠다																																
    FIELD: sdyn_conn-carrid,																																
           sdyn_conn-connid,																																
           sdyn_conn-fldate.																																
    MODULE check_sflight ON CHAIN-REQUEST.																																
  ENDCHAIN.																																
																																
  CHAIN.																																
    FIELD: sdyn_conn-seatsmax,																																
           sdyn_conn-planetype.																																
    MODULE check_planetype ON CHAIN-REQUEST.																																
  ENDCHAIN.																																
																																
  CALL SUBSCREEN sub.																																
																																
  MODULE user_command_0100.																																
