****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZBOOKINGS_UPDATE_SS36																																
0201																																
750																																
                40																																
%_HEADER																																
SAPMZBOOKINGS_UPDATE_SS36               0201I0201      7 73192 37  0  0 21 83  0G D                              20240906170225																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SDYN_CONN-CARRID	2	CHAR	 16	30	00	04	30	00	  1	  2		  0	  0	  0		  0			CAR		  0	  0								항공사	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CARRID	C	CHAR	  3	A0	00	84	30	08	  1	 20		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
SDYN_CONN-CITYFROM	2	CHAR	 11	30	00	00	30	00	  1	 37		  0	  0	  0		  0					  0	  0								출발 도시	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CITYFROM	C	CHAR	 20	A0	00	80	30	00	  1	 55		  0	  0	  0		  0					 40	  0								____________________	                                       00	
SDYN_CONN-CONNID	2	CHAR	 15	30	00	04	30	00	  2	  2		  0	  0	  0		  0			CON		  0	  0								항공편 번호	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CONNID	N	NUMC	  4	A0	00	84	30	08	  2	 20		  0	  0	  0		  0			CON		  8	  0								____	X                                      00	
SDYN_CONN-CITYTO	2	CHAR	 17	30	00	00	30	00	  2	 37		  0	  0	  0		  0					  0	  0								도착 도시	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CITYTO	C	CHAR	 20	A0	00	80	30	00	  2	 55		  0	  0	  0		  0					 40	  0								____________________	                                       00	
SDYN_CONN-FLDATE	2	CHAR	  9	30	00	00	30	00	  3	  2		  0	  0	  0		  0			DAY		  0	  0								일자	                                                                                                                                                                                                                                                        X	
SDYN_CONN-FLDATE	D	DATE	 10	A0	00	80	30	08	  3	 20		  0	  0	  0		  0			DAY		 16	  0								__________	X                                      00	
SDYN_CONN-SEATSMAX	0	CHAR	 14	30	00	00	30	00	  5	  2		  0	  0	  0		 14					  0	  0								Capacity eco.	                                                                                                                                                                                                                                                        X	
SDYN_CONN-SEATSMAX	X	INT4	 10	A0	00	81	30	08	  5	 20		  0	  0	  0		  0					 10	  0								__________	X                                      00	
SDYN_CONN-SEATSOCC	2	CHAR	 15	30	00	00	30	00	  6	  2		  0	  0	  0		  0					  0	  0								예약된 일반석	                                                                                                                                                                                                                                                        X	
SDYN_CONN-SEATSOCC	X	INT4	 10	A0	00	81	30	08	  6	 20		  0	  0	  0		  0					 10	  0								__________	X                                      00	
SDYN_CONN-PAYMENTSUM	2	CHAR	 10	30	00	00	30	00	  7	  2		  0	  0	  0		  0					  0	  0								총계	                                                                                                                                                                                                                                                        X	
SDYN_CONN-PAYMENTSUM	P	CURR	 22	A0	00	80	30	00	  7	 20		  0	  0	  0		  0					 17	  2		SDYN_CONN-CURRENCY						______________________	                                       00	
SDYN_CONN-CURRENCY	C	CUKY	  5	A0	00	84	30	08	  7	 44		  0	  0	  0		  0					 10	  0								_____	X                                      00	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
																																
PROCESS BEFORE OUTPUT.																																
*																																
PROCESS AFTER INPUT.																																
