****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZBOOKINGS_UPDATE_SS36																																
0100																																
750																																
                40																																
%_HEADER																																
SAPMZBOOKINGS_UPDATE_SS36               0100 0100      5 27192 37  0  0 21 83  0G D                              20240906170225																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SDYN_CONN-CARRID	2	CHAR	 16	30	00	04	30	00	  3	  2		  0	  0	  0		  0			CAR		  0	  0								항공사	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CARRID	C	CHAR	  3	A0	0C	A4	00	08	  3	 19		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
SDYN_CONN-CONNID	2	CHAR	 15	30	00	04	30	00	  4	  2		  0	  0	  0		  0			CON		  0	  0								항공편 번호	                                                                                                                                                                                                                                                        X	
SDYN_CONN-CONNID	N	NUMC	  4	A0	0C	A4	00	08	  4	 19		  0	  0	  0		  0			CON		  8	  0								____	X                                      00	
SDYN_CONN-FLDATE	2	CHAR	  9	30	00	00	30	00	  5	  2		  0	  0	  0		  0			DAY		  0	  0								일자	                                                                                                                                                                                                                                                        X	
SDYN_CONN-FLDATE	D	DATE	 10	A0	0C	A8	00	08	  5	 19		  0	  0	  0		  0			DAY		 16	  0								__________	X                                      00	
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
																																
PROCESS BEFORE OUTPUT.																																
  MODULE status_0100.																																
  MODULE clear_okcode.																																
																																
																																
PROCESS AFTER INPUT.																																
  MODULE exit AT EXIT-COMMAND.																																
  CHAIN.																																
*   cancel booking: check if flight exists or flight can be created																																
    FIELD: sdyn_conn-carrid, sdyn_conn-connid, sdyn_conn-fldate.																																
    MODULE check_flight.																																
  ENDCHAIN.																																
  MODULE user_command_0100.																																
