****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZDEMO_SS36																																
0200																																
750																																
                40																																
%_HEADER																																
SAPMZDEMO_SS36                          0200 0200      5 29192 37  0  0 27121  0G E                              20240829103114																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
ZCALCULATOR_SS36-ARG1	2	CHAR	 20	30	00	00	30	00	  2	  4		  0	  0	  0		  0					  0	  0								Argument1	                                                                                                                                                                                                                                                        X	
ZCALCULATOR_SS36-ARG1	X	INT2	  6	A0	00	90	00	00	  2	 25		  0	  0	  0		  0					  5	  0								_____V	                                       00	
ZCALCULATOR_SS36-OPERATOR	2	CHAR	 20	30	00	01	30	00	  3	  4		  0	  0	  0		  0					  0	  0								Operator	                                                                                                                                                                                                                                                        X	
ZCALCULATOR_SS36-OPERATOR	C	CHAR	  1	A0	00	A1	00	08	  3	 25		  0	  0	  0		  0					  2	  0								_	X                                      00	
ZCALCULATOR_SS36-ARG2	2	CHAR	 20	30	00	00	30	00	  4	  4		  0	  0	  0		  0					  0	  0								Argument2	                                                                                                                                                                                                                                                        X	
ZCALCULATOR_SS36-ARG2	X	INT2	  6	A0	00	90	00	00	  4	 25		  0	  0	  0		  0					  5	  0								_____V	                                       00	
ZCALCULATOR_SS36-RESULT	2	CHAR	 20	30	00	00	30	00	  5	  4		  0	  0	  0		  0					  0	  0								Result	                                                                                                                                                                                                                                                        X	
ZCALCULATOR_SS36-RESULT	X	INT2	  6	A0	00	90	30	00	  5	 25		  0	  0	  0		  0					  5	  0								_____V	                                       00	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0200.																																
  MODULE init.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0200.																																
																																
  MODULE calculate_dic.																																
