****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZDEMO_SS36																																
0100																																
750																																
                40																																
%_HEADER																																
SAPMZDEMO_SS36                          0100 0100      7 29192 37  0  0 27121  0G E                              20240828161948																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
LBL_ARG1	0	CHAR	 10	00	00	00	30	00	  3	  7		  0	  0	  0		  0					  0	  0								Argument 1	                                                                                                                                                                                                                                                        X	
GV_ARG1	I	INT4	 11	80	00	80	00	00	  3	 20		  0	  0	  0		  0					  0	  0								___________		
LBL_OPERATOR	0	CHAR	  8	00	00	00	30	00	  4	  7		  0	  0	  0		  0					  0	  0								Operator	                                                                                                                                                                                                                                                        X	
GV_OPERATOR	C	CHAR	  1	80	00	80	00	00	  4	 20		  0	  0	  0		  0					  0	  0										
LBL_ARG2	0	CHAR	 10	00	00	00	30	00	  5	  7		  0	  0	  0		  0					  0	  0								Argument 2	                                                                                                                                                                                                                                                        X	
GV_ARG2	I	INT4	 11	80	00	80	00	00	  5	 20		  0	  0	  0		  0					  0	  0								___________		
LBL_RESULT	0	CHAR	  6	00	00	00	30	00	  7	  7		  0	  0	  0		  0					  0	  0								Result	                                                                                                                                                                                                                                                        X	
GV_RESULT	I	INT4	 11	80	00	80	00	00	  7	 20		  0	  0	  0		  0					  0	  0								___________		
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0100.																																
																																
*  MODULE calculate2.																																
																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0100.																																
																																
  MODULE calculate. "계산기 모듈																																
