****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZBC405_SS36_ALV																																
0100																																
750																																
                40																																
%_HEADER																																
ZBC405_SS36_ALV                         0100 0100     26101192 37  0  0 27121  0G E                              20240910110308																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
MY_CONTROL_AREA			100	00	30	00	30	00	  2	  3		  0	  0	  0		 25	U				 10	 56	101									
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________	                                       00	
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE clear_ok_code.																																
 MODULE STATUS_0100.																																
 MODULE create_and_transfer.																																
*																																
PROCESS AFTER INPUT.																																
 MODULE USER_COMMAND_0100.																																
