****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZSCHEDULE_SS36																																
0100																																
750																																
                40																																
%_HEADER																																
SAPMZSCHEDULE_SS36                      0100 0100     17 93192 37  0  0 27123  0G E                              20240904112549																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SPFLI-CARRID	2	CHAR	 16	30	00	04	30	00	  1	  2		  0	  0	  0		  0			CAR		  0	  0								항공사	                                                                                                                                                                                                                                                        X	
SPFLI-CARRID	C	CHAR	  3	A0	00	84	00	08	  1	 19		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
SPFLI-CONNID	2	CHAR	 15	30	00	00	30	00	  2	  2		  0	  0	  0		  0			CON		  0	  0								항공편 번호	                                                                                                                                                                                                                                                        X	
SPFLI-CONNID	N	NUMC	  4	A0	00	80	00	00	  2	 19		  0	  0	  0		  0			CON		  8	  0								____	                                       00	
BTN_SEARCH		CHAR	 23	00	00	00	30	00	  4	  2		  0	  0	  0		 21	P				  0	  0	102							@13@ Search	                                                                                                                                                                        SEAR	
BTN_ASC		CHAR	 15	00	00	00	30	00	  6	  2		  0	  0	  0		 12	P				  0	  0	103							@3E@ Ascending	                                                                                                                                                                        ASCE	
BTN_DESC		CHAR	 17	00	00	00	30	00	  6	 15		  0	  0	  0		 13	P				  0	  0	104							@3F@ Descending	                                                                                                                                                                        DESC	
MY_TABLE			 93	F5	C0	00	00	00	  7	  2	E	101	  1	  1		 10	T				  0	  0									                                                                                                                                                                                                                                    SORT	
ZSSFLIGHT_SS36-FLDATE	2	CHAR	  9	30	00	00	30	80	  1	  1	T	101	  1	  1		 10			DAY		  0	  0								일자		
ZSSFLIGHT_SS36-PRICE	2	CHAR	  9	30	00	00	30	80	  1	  2	T	101	  1	  1		 20					  0	  0								항공 요금		
ZSSFLIGHT_SS36-CURRENCY	2	CHAR	 16	30	00	04	30	80	  1	  3	T	101	  1	  1		  5					  0	  0								항공사 통화		
ZSSFLIGHT_SS36-PLANETYPE	2	CHAR	 11	30	00	04	30	80	  1	  4	T	101	  1	  1		 10					  0	  0								항공기 유형		
ZSSFLIGHT_SS36-SEATSMAX	2	CHAR	 20	30	00	01	30	80	  1	  5	T	101	  1	  1		 10					  0	  0								일반석 최대 정원		
ZSSFLIGHT_SS36-SEATSOCC	2	CHAR	 15	30	00	01	30	80	  1	  6	T	101	  1	  1		 10					  0	  0								예약된 일반석		
ZSSFLIGHT_SS36-PAYMENTSUM	2	CHAR	 10	30	00	00	30	80	  1	  7	T	101	  1	  1		 22					  0	  0								총계		
ZSSFLIGHT_SS36-SEATSMAX_B	2	CHAR	 20	30	00	01	30	80	  1	  8	T	101	  1	  1		 10					  0	  0								비즈니스석 최대 정원		
ZSSFLIGHT_SS36-SEATSOCC_B	2	CHAR	 15	30	00	01	30	80	  1	  9	T	101	  1	  1		 10					  0	  0								비즈니스석 점유		
ZSSFLIGHT_SS36-SEATSMAX_F	2	CHAR	 20	30	00	01	30	80	  1	 10	T	101	  1	  1		 10					  0	  0								일등석의 최대 정원		
ZSSFLIGHT_SS36-SEATSOCC_F	2	CHAR	 15	30	00	01	30	80	  1	 11	T	101	  1	  1		 10					  0	  0								일등석 점유		
ZSSFLIGHT_SS36-FLDATE	D	DATE	 10	A0	00	80	30	28	  1	  1	T	101	  1	  1		 10			DAY		 16	  0								__________	X                                      00	
ZSSFLIGHT_SS36-PRICE	P	CURR	 20	A0	00	80	30	20	  1	  2	T	101	  1	  1		 20					 15	  2		ZSSFLIGHT_SS36-CURRENCY						____________________	                                       00	
ZSSFLIGHT_SS36-CURRENCY	C	CUKY	  5	A0	00	84	30	28	  1	  3	T	101	  1	  1		  5					 10	  0								_____	X                                      00	
ZSSFLIGHT_SS36-PLANETYPE	C	CHAR	 10	A0	00	84	00	08	  1	  4	T	101	  1	  1		 10					 20	  0								__________	X                                      00	
ZSSFLIGHT_SS36-SEATSMAX	X	INT4	 10	A0	00	81	30	08	  1	  5	T	101	  1	  1		 10					 10	  0								__________	X                                      00	
ZSSFLIGHT_SS36-SEATSOCC	X	INT4	 10	A0	00	81	30	08	  1	  6	T	101	  1	  1		 10					 10	  0								__________	X                                      00	
ZSSFLIGHT_SS36-PAYMENTSUM	P	CURR	 22	A0	00	80	30	00	  1	  7	T	101	  1	  1		 22					 17	  2		ZSSFLIGHT_SS36-CURRENCY						______________________	                                       00	
ZSSFLIGHT_SS36-SEATSMAX_B	X	INT4	 10	A0	00	81	30	08	  1	  8	T	101	  1	  1		 10					 10	  0								__________	X                                      00	
ZSSFLIGHT_SS36-SEATSOCC_B	X	INT4	 10	A0	00	81	30	08	  1	  9	T	101	  1	  1		 10					 10	  0								__________	X                                      00	
ZSSFLIGHT_SS36-SEATSMAX_F	X	INT4	 10	A0	00	81	30	08	  1	 10	T	101	  1	  1		 10					 10	  0								__________	X                                      00	
ZSSFLIGHT_SS36-SEATSOCC_F	X	INT4	 10	A0	00	81	30	08	  1	 11	T	101	  1	  1		 10					 10	  0								__________	X                                      00	
LBL_FIXED	0	CHAR	 12	00	00	00	30	00	 17	  2		  0	  0	  0		  0					  0	  0								Fixed Column		
GV_FIXED	N	NUMC	  2	80	00	80	00	00	 17	 15		  0	  0	  0		  0					  4	  0								__		
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
* MODULE STATUS_0100.																																
  MODULE clear_ok_code.																																
* 인터널 테이블에 있는 내용을 테이블 컨트롤(화면)로 전송																																
* 그려진 화면이 6개면 6번의 LOOP만 돈다																																
* 이때 화면 전송 순서가 테이블 컨트롤 먼저, 그 다음 나머지 값을 보냄																																
  LOOP AT gt_flight INTO gw_flight																																
                    WITH CONTROL my_table.																																
    "과거 날짜의 Plane Type은 변경이 불가능하도록 설정																																
    MODULE modify_screen.																																
																																
    MODULE transfer_data_to.																																
																																
  ENDLOOP.																																
																																
*																																
PROCESS AFTER INPUT.																																
																																
  "화면의 fixed column의 필드의 값이 바뀌면 모듈 실행																																
  FIELD gv_fixed																																
        MODULE change_tc ON REQUEST.																																
																																
  "화면을 테이블 컨트롤을 LOOP도는 것(internal table을 LOOP 도는 것이 아님)																																
  LOOP AT gt_flight.																																
* 화면에서 변경된 값을 인터널 테이블로 업데이트																																
* 값을 바꾸고 enter 쳤을 때 pai 발생함 이때 변경 값 업데이트																																
    FIELD: zssflight_ss36-price. "금액이 화폐단위보다 늦게 전달되게 하기 위함.																																
    "(field문은 제일 마지막 전달되기 때문에)																																
    MODULE transfer_screen_to_data. "차례대로 화면의 데이터를 Internal Table로																																
																																
  ENDLOOP.																																
																																
  MODULE user_command_0100.																																
