****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZFSCHEDULE_SS36_2																																
0100																																
750																																
                40																																
%_HEADER																																
ZFSCHEDULE_SS36_2                       0100 0100     25117192 37  0  0 27122  0G E                              20240911091314																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SFLIGHT-CARRID	2	CHAR	 16	30	00	04	30	00	  2	  4		  0	  0	  0		  0			CAR		  0	  0								Ç×°ø»ç	                                                                                                                                                                                                                                                        X	
SFLIGHT-CARRID	C	CHAR	  3	A0	00	84	30	08	  2	 21		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
CONTROL_AREA			115	00	30	00	30	00	  4	  4		  0	  0	  0		 22	U				 11	 57	101									
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE STATUS_0100.																																
 MODULE init_control_processing.																																
																																
*																																
PROCESS AFTER INPUT.																																
 MODULE USER_COMMAND_0100.																																
