****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZREPORT_SS36																																
1100																																
750																																
                40																																
%_HEADER																																
ZREPORT_SS36                            1100S1100      3 34200 36  0  0200120  0G ESEL_SCREEN 1100 INFO:17000034020240909144245																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
PA_FIRST	C	CHAR	  1	80	00	80	00	00	  1	  2		  0	  0	  0		  1	C				  0	  0	101					PAR	001	_		
%_PA_FIRST_%_APP_%-TEXT	C	CHAR	 30	80	02	80	31	00	  1	  4		  0	  0	  0		 30					  0	  0						TXT	001		                                                                                                                                                                                                                                                         X	
PA_LAST	C	CHAR	  1	80	00	80	00	00	  2	  2		  0	  0	  0		  1	C				  0	  0	102					PAR	002	_		
%_PA_LAST_%_APP_%-TEXT	C	CHAR	 30	80	02	80	31	00	  2	  4		  0	  0	  0		 30					  0	  0						TXT	002		                                                                                                                                                                                                                                                         X	
%_17NNS0001485962_%_%_%_%_%_%_	C	CHAR	  1	00	00	00	00	00	  3	  2		  0	  0	  0		  0					  0	  0							SRI	-		
SSCRFIELDS-UCOMM	C	CHAR	 70	A0	10	00	00	00	255	  5	O	  0	  0	  0		 70					140	  0								______________________________________________________________________	                                       00	
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
																																
MODULE %_INIT_PBO.																																
																																
MODULE %_PBO_REPORT.																																
																																
MODULE %_PF_STATUS.																																
																																
MODULE %_END_OF_PBO.																																
																																
PROCESS AFTER INPUT.																																
																																
  MODULE %_BACK AT EXIT-COMMAND.																																
																																
  MODULE %_INIT_PAI.																																
																																
FIELD !PA_FIRST MODULE %_PA_FIRST .																																
																																
FIELD !PA_LAST MODULE %_PA_LAST .																																
																																
CHAIN.																																
  FIELD PA_FIRST .																																
  FIELD PA_LAST .																																
  MODULE %_END_OF_SCREEN.																																
  MODULE %_OK_CODE_1000.																																
ENDCHAIN.																																
