****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZREPORT_SS36																																
0120																																
750																																
                40																																
%_HEADER																																
ZREPORT_SS36                            0120J0120      2 44200 36  0  0200120  0G ESEL_SCREEN 0120 INFO:17000034020240909144245																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
%_PA_BID_%_APP_%-TEXT	C	CHAR	 30	80	02	80	31	00	  1	  2		  0	  0	  0		 30					  0	  0						TXT	001		                                                                                                                                                                                                                                                        X	
PA_BID	N	NUMC	  8	80	20	80	00	18	  1	 36		  0	  0	  0		  8					  0	  0						PAR	001	________		
%_17NNJ0001485962_%_%_%_%_%_%_	C	CHAR	  1	00	00	00	00	00	  2	  2		  0	  0	  0		  0					  0	  0							SRI	-		
SSCRFIELDS-UCOMM	C	CHAR	 70	A0	10	00	00	00	255	  5	O	  0	  0	  0		 70					140	  0								______________________________________________________________________	                                       00	
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
																																
MODULE %_INIT_PBO_J.																																
																																
MODULE %_PBO_REPORT.																																
																																
MODULE %_PF_STATUS.																																
																																
MODULE %_END_OF_PBO.																																
																																
PROCESS AFTER INPUT.																																
																																
  MODULE %_INIT_PAI_J.																																
																																
FIELD !PA_BID MODULE %_PA_BID .																																
																																
CHAIN.																																
  FIELD PA_BID .																																
  MODULE %_END_OF_SCREEN.																																
  MODULE %_OK_CODE_1000.																																
ENDCHAIN.																																
