****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZREPORT_SS36																																
0110																																
750																																
                40																																
%_HEADER																																
ZREPORT_SS36                            0110J0110      3 65200 36  0  0200120  0G ESEL_SCREEN 0110 INFO:17000034020240909144245																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
%_PA_CAR_%_APP_%-TEXT	C	CHAR	 30	80	02	80	31	00	  1	  2		  0	  0	  0		 30					  0	  0						TXT	001		                                                                                                                                                                                                                                                        X	
PA_CAR	C	CHAR	  3	80	0C	80	00	18	  1	 36		  0	  0	  0		  3			CAR		  0	  0						PAR	001	___		
%_SO_CON_%_APP_%-TEXT	C	CHAR	 30	80	02	80	31	00	  2	  2		  0	  0	  0		 30					  0	  0						TXT	002		                                                                                                                                                                                                                                    %_SSCR_%_S_SO_CON   X	
%_SO_CON_%_APP_%-OPTI_PUSH	C	CHAR	 40	80	00	80	32	00	  2	 33		  0	  0	  0		  2					  0	  0						OPU	002		                                                                                                                                                                                                                                    %_SSCR_%_S_SO_CON	
SO_CON-LOW	N	NUMC	  4	80	20	80	00	18	  2	 36		  0	  0	  0		  4					  0	  0						LOW	002	____	                                                                                                                                                                                                                                    %_SSCR_%_S_SO_CON	
%_SO_CON_%_APP_%-TO_TEXT	C	CHAR	  5	80	02	80	31	00	  2	 55		  0	  0	  0		  5					  0	  0						TOT	002		                                                                                                                                                                                                                                    %_SSCR_%_S_SO_CON   X	
SO_CON-HIGH	N	NUMC	  4	80	20	80	00	18	  2	 61		  0	  0	  0		  4					  0	  0						HGH	002	____	                                                                                                                                                                                                                                    %_SSCR_%_S_SO_CON	
%_17SNJ0001485962_%_%_%_%_%_%_	C	CHAR	  1	00	00	00	00	00	  3	  2		  0	  0	  0		  0					  0	  0							SRI	-		
SSCRFIELDS-UCOMM	C	CHAR	 70	A0	10	00	00	00	255	  5	O	  0	  0	  0		 70					140	  0								______________________________________________________________________	                                       00	
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
																																
MODULE %_INIT_PBO_J.																																
																																
MODULE %_PBO_REPORT.																																
																																
MODULE %_PF_STATUS.																																
																																
MODULE %_SO_CON.																																
																																
MODULE %_END_OF_PBO.																																
																																
PROCESS AFTER INPUT.																																
																																
  MODULE %_INIT_PAI_J.																																
																																
FIELD !PA_CAR MODULE %_PA_CAR .																																
																																
CHAIN.																																
  FIELD  SO_CON-LOW.																																
  FIELD  SO_CON-HIGH.																																
  MODULE %_SO_CON.																																
ENDCHAIN.																																
																																
CHAIN.																																
  FIELD PA_CAR .																																
  FIELD  SO_CON-LOW.																																
  FIELD  SO_CON-HIGH.																																
  MODULE %_END_OF_SCREEN.																																
  MODULE %_OK_CODE_1000.																																
ENDCHAIN.																																
