****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZTRAVELAG_SS36																																
0200																																
750																																
                40																																
%_HEADER																																
ZTRAVELAG_SS36                          0200M0200     11 82192 37  0  0 21 83  0G D                              20240905133216																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
TC_STRAVELAG			 82	F0	F0	00	00	00	  1	  2	E	101	  1	  1		 11	T				  0	  0										
STRAVELAG-AGENCYNUM	2	CHAR	 12	30	00	04	30	80	  1	  1	T	101	  1	  1		  8			AGENCYNUM		  0	  0								여행사 번호		
STRAVELAG-NAME	2	CHAR	 19	30	02	00	30	80	  1	  2	T	101	  1	  1		 25					  0	  0								여행사 이름		
STRAVELAG-STREET	2	CHAR	 15	30	02	00	30	80	  1	  3	T	101	  1	  1		 30					  0	  0								상세 주소		
STRAVELAG-POSTBOX	2	CHAR	  8	30	00	00	30	80	  1	  4	T	101	  1	  1		 10					  0	  0								사서함		
STRAVELAG-POSTCODE	2	CHAR	 14	30	00	00	30	80	  1	  5	T	101	  1	  1		 10					  0	  0								우편번호		
STRAVELAG-CITY	2	CHAR	 15	30	02	00	30	80	  1	  6	T	101	  1	  1		 25					  0	  0								도시		
STRAVELAG-COUNTRY	2	CHAR	 15	30	00	00	30	80	  1	  7	T	101	  1	  1		  3					  0	  0								국가		
STRAVELAG-REGION	2	CHAR	 15	30	00	00	30	80	  1	  8	T	101	  1	  1		  3					  0	  0								지역		
STRAVELAG-TELEPHONE	2	CHAR	  7	30	00	00	30	80	  1	  9	T	101	  1	  1		 30					  0	  0								전화		
STRAVELAG-URL	2	CHAR	 18	30	02	00	30	80	  1	 10	T	101	  1	  1		 50					  0	  0								여행사 URL		
STRAVELAG-LANGU	2	CHAR	 15	30	02	04	30	80	  1	 11	T	101	  1	  1		  2			SPR		  0	  0								언어		
STRAVELAG-AGENCYNUM	N	NUMC	  8	A0	20	84	30	28	  1	  1	T	101	  1	  1		  8	0		AGENCYNUM		 16	  0								________	X                                      00	
STRAVELAG-NAME	C	CHAR	 25	A0	02	80	30	20	  1	  2	T	101	  1	  1		 25					 50	  0								_________________________	                                       00	
STRAVELAG-STREET	C	CHAR	 30	A0	02	80	00	00	  1	  3	T	101	  1	  1		 30					 60	  0								______________________________	                                       00	
STRAVELAG-POSTBOX	C	CHAR	 10	A0	00	80	00	00	  1	  4	T	101	  1	  1		 10					 20	  0								__________	                                       00	
STRAVELAG-POSTCODE	C	CHAR	 10	A0	00	80	00	00	  1	  5	T	101	  1	  1		 10					 20	  0								__________	                                       00	
STRAVELAG-CITY	C	CHAR	 25	A0	02	80	00	00	  1	  6	T	101	  1	  1		 25					 50	  0								_________________________	                                       00	
STRAVELAG-COUNTRY	C	CHAR	  3	A0	00	80	00	00	  1	  7	T	101	  1	  1		  3					  6	  0								___	                                       00	
STRAVELAG-REGION	C	CHAR	  3	A0	00	80	00	00	  1	  8	T	101	  1	  1		  3					  6	  0								___	                                       00	
STRAVELAG-TELEPHONE	C	CHAR	 30	A0	00	80	00	00	  1	  9	T	101	  1	  1		 30					 60	  0								______________________________	                                       00	
STRAVELAG-URL	C	CHAR	255	A1	02	80	00	00	  1	 10	T	101	  1	  1		 50					255	  0								____________________________________________________________________________________________________________________________________	                                       00	
STRAVELAG-LANGU	C	LANG	  2	A0	02	84	00	08	  1	 11	T	101	  1	  1		  2			SPR	ISOLA	  2	  0								__	X                                      00	
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
																																
PROCESS BEFORE OUTPUT.																																
  MODULE status_0200.																																
  MODULE get_data.																																
* fill table control (only agencies, marked on list)																																
  LOOP AT gt_travelag_sel INTO gs_travelag																																
       WITH CONTROL tc_stravelag.																																
    MODULE trans_to_0200.																																
  ENDLOOP.																																
  MODULE clear_okcode.																																
																																
*																																
PROCESS AFTER INPUT.																																
  MODULE exit AT EXIT-COMMAND.																																
																																
  LOOP AT gt_travelag_sel.																																
    "사용자가 입력한 값을 LOOP 돌며 쌓기																																
    MODULE trans_from_0200.																																
  ENDLOOP.																																
  MODULE user_command_0200.																																
