****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
SAPMZBOOKINGS_SS36																																
0200																																
750																																
                40																																
%_HEADER																																
SAPMZBOOKINGS_SS36                      0200 0200     21 82192 37  0  0 21 83  0G D                              20240905155756																																
%_DESCRIPTION																																
                40																																
%_FIELDS																																
SUB1			 82	00	30	00	30	00	  1	  2		  0	  0	  0		 10	B				  8	 80	102									
TC_SBOOK			 81	F0	F4	00	00	00	 12	  3	E	101	  1	  1		 10	T				  0	  0										
TC_SBOOK_TITLE		CHAR	 28	00	00	00	30	40	  1	  0	T	101	  1	  1		 28					  0	  0								Bookings for selected flight	                                       00	
SDYN_BOOK-BOOKID	2	CHAR	 15	30	00	00	30	A0	  1	  1	T	101	  1	  1		  8			BOK		  0	  0								예약 번호		
SDYN_BOOK-CUSTOMID	2	CHAR	 15	30	00	04	30	A0	  1	  2	T	101	  1	  1		  8			CSM		  0	  0								고객 번호		
SDYN_BOOK-NAME	2	CHAR	 15	30	02	00	30	80	  1	  3	T	101	  1	  1		 25					  0	  0								고객이름		
*SDYN_BOOK-CANCELLED	2	CHAR	 17	30	00	01	30	80	  1	  4	T	101	  1	  1		  6					  0	  0								취소 표시		
*SDYN_BOOK-SMOKER	2	CHAR	 15	30	00	01	30	80	  1	  5	T	101	  1	  1		  7					  0	  0								흡연자		
SDYN_BOOK-LUGGWEIGHT	2	CHAR	 15	30	00	00	30	80	  1	  6	T	101	  1	  1		 10					  0	  0								수하물 중량		
SDYN_BOOK-WUNIT	2	CHAR	 15	30	00	00	30	80	  1	  7	T	101	  1	  1		  3					  0	  0								단위		
*SDYN_BOOK-INVOICE	2	CHAR	 12	30	00	01	30	80	  1	  8	T	101	  1	  1		  8					  0	  0								송장플래그		
SDYN_BOOK-CUSTTYPE	2	CHAR	 15	30	00	01	30	80	  1	  9	T	101	  1	  1		  3					  0	  0								B/P 고객		
SDYN_BOOK-LOCCURAM	2	CHAR	 15	30	00	00	30	80	  1	 10	T	101	  1	  1		 20					  0	  0								금액		
SDYN_BOOK-LOCCURKEY	2	CHAR	 16	30	00	04	30	80	  1	 11	T	101	  1	  1		  5					  0	  0								항공사 통화		
SDYN_BOOK-CLASS	2	CHAR	  8	30	00	01	30	80	  1	 12	T	101	  1	  1		  6					  0	  0								클래스		
SDYN_BOOK-ORDER_DATE	2	CHAR	 15	30	00	00	30	80	  1	 13	T	101	  1	  1		 13					  0	  0								예약일		
SDYN_BOOK-BOOKID	N	NUMC	  8	A0	00	80	38	28	  1	  1	T	101	  1	  1		  8			BOK		 16	  0								________	X                                      00	
SDYN_BOOK-CUSTOMID	N	NUMC	  8	A0	00	84	38	28	  1	  2	T	101	  1	  1		  8			CSM		 16	  0								________	X                                      00	
SDYN_BOOK-NAME	C	CHAR	 25	A0	02	80	30	00	  1	  3	T	101	  1	  1		 25					 50	  0								_________________________	                                       00	
SDYN_BOOK-CANCELLED	C	CHAR	  1	A0	00	81	00	08	  1	  4	T	101	  1	  1		  6	C				  2	  0	103							_	X                                      00	
SDYN_BOOK-SMOKER	C	CHAR	  1	A0	00	81	30	08	  1	  5	T	101	  1	  1		  7	C				  2	  0	104							_	X                                      00	
SDYN_BOOK-LUGGWEIGHT	P	QUAN	 10	A0	00	80	30	00	  1	  6	T	101	  1	  1		 10					  8	  4		SDYN_BOOK-WUNIT						_.___,____	                                       00	
SDYN_BOOK-WUNIT	C	UNIT	  3	A0	02	80	30	00	  1	  7	T	101	  1	  1		  3				CUNIT	  6	  0								___	                                       00	
SDYN_BOOK-INVOICE	C	CHAR	  1	A0	00	81	30	08	  1	  8	T	101	  1	  1		  8	C				  2	  0	105							_	X                                      00	
SDYN_BOOK-CUSTTYPE	C	CHAR	  1	A0	00	81	30	08	  1	  9	T	101	  1	  1		  3					  2	  0								_	X                                      00	
SDYN_BOOK-LOCCURAM	P	CURR	 20	A0	00	80	30	00	  1	 10	T	101	  1	  1		 20					 15	  2		SDYN_BOOK-LOCCURKEY						____________________	                                       00	
SDYN_BOOK-LOCCURKEY	C	CUKY	  5	A0	00	84	30	08	  1	 11	T	101	  1	  1		  5					 10	  0								_____	X                                      00	
SDYN_BOOK-CLASS	C	CHAR	  1	A0	00	81	30	08	  1	 12	T	101	  1	  1		  6					  2	  0								_	X                                      00	
SDYN_BOOK-ORDER_DATE	D	DATE	 10	A0	00	80	30	08	  1	 13	T	101	  1	  1		 13					 16	  0								__________	X                                      00	
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
																																
PROCESS BEFORE OUTPUT.																																
  MODULE status_0200.																																
  MODULE read_bookings.																																
  CALL SUBSCREEN sub1 INCLUDING sy-cprog '0201'.																																
  LOOP AT gt_bookings INTO gs_bookings WITH CONTROL tc_sbook.																																
    MODULE trans_to_tc.																																
*   allow only modification of bookings, that are not allready cancelled																																
    MODULE modify_screen.																																
  ENDLOOP.																																
  MODULE clear_okcode.																																
																																
																																
PROCESS AFTER INPUT.																																
  MODULE exit AT EXIT-COMMAND.																																
  LOOP AT gt_bookings.																																
*   mark changed bookings in internal table itab_book																																
    FIELD sdyn_book-cancelled																																
    MODULE modify_itab ON REQUEST.																																
  ENDLOOP.																																
  MODULE user_command_0200.																																
